version: '3'

services:
  anomaly-detection:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp

volumes:
  data:
